name: Build and deploy ASP.NET Core API - ServiceApp

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Required for OIDC

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  ASPNETCORE_ENVIRONMENT: Production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          dotnet-quality: preview

      - name: Restore
        run: dotnet restore serviceApp.Server/serviceApp.Server.csproj

      - name: Publish API only
        run: dotnet publish serviceApp.Server/serviceApp.Server.csproj -c Release -o publish /p:ContinuousIntegrationBuild=true

      - name: Assert no Blazor client artifacts
        run: |
          if [ -d publish/wwwroot/_framework ]; then
            echo "ERROR: Client artifacts found. Remove the UI project reference from the Server csproj."
            ls -la publish/wwwroot/_framework | head -n 30
            exit 1
          fi

      - name: Archive package
        run: |
            cd publish
            zip -r ../publish.zip .
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: publish.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: progorb
          package: publish.zip











